import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { toast } from 'sonner'

import { Card, PrimaryButton, SectionHeading, StatusChip, WordChip } from '../components/ui'
import {
  type ExerciseFeedback,
  useCompleteLessonMutation,
  useLessonAttemptQuery,
  useLessonQuery,
  useSubmitAnswerMutation,
} from '../features/lessons/lessons'

const exerciseLabels = {
  vocabulary_context: 'Vocabulary context',
  syntax: 'Syntax understanding',
  paragraph_logic: 'Paragraph logic',
  output: 'Output practice',
}

export function LessonPage() {
  const { lessonId } = useParams()
  const navigate = useNavigate()
  const lesson = useLessonQuery(lessonId)
  const attempt = useLessonAttemptQuery(lessonId)
  const submitAnswer = useSubmitAnswerMutation(lessonId)
  const completeLesson = useCompleteLessonMutation(lessonId)
  const [answers, setAnswers] = useState<Record<number, string>>({})
  const [submittedFeedback, setSubmittedFeedback] = useState<Record<number, ExerciseFeedback>>({})
  const [prediction, setPrediction] = useState('')
  const [showKnowledgeAnswer, setShowKnowledgeAnswer] = useState(false)

  if (lesson.isPending) {
    return <Card className="p-8"><StatusChip tone="default">Loading lesson</StatusChip><p className="mt-4 text-sm text-ink-muted">Reading the saved ContextLesson…</p></Card>
  }

  if (lesson.isError || !lesson.data) {
    return <Card className="p-8"><StatusChip tone="danger">Lesson unavailable</StatusChip><p className="mt-4 text-sm text-ink-muted">{lesson.error instanceof Error ? lesson.error.message : 'The lesson could not be loaded.'}</p><Link className="mt-5 inline-block text-sm font-semibold text-lexis" to="/app/workspace">Back to Workspace</Link></Card>
  }

  const data = lesson.data
  const savedFeedback = new Map(
    (attempt.data?.feedback ?? []).map((feedback) => [feedback.exerciseIndex, feedback]),
  )
  for (const [index, feedback] of Object.entries(submittedFeedback)) {
    savedFeedback.set(Number(index), feedback)
  }

  return (
    <div className="pt-1">
      <div className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-4">
        <div>
          <h1 className="text-2xl font-semibold tracking-[-0.025em]">{data.content.title}</h1>
          <p className="mt-1 text-xs text-ink-muted">{data.cefrLevel} · {data.examGoal} · {data.content.targetWords.length} target words</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <StatusChip>Schema valid</StatusChip>
          <StatusChip tone={savedFeedback.size === data.content.exercises.length ? 'success' : 'default'}>
            {savedFeedback.size} / {data.content.exercises.length} answered
          </StatusChip>
        </div>
      </div>
      <Card className="mt-5 p-5 md:p-7">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <SectionHeading subtitle="Prediction is optional. You can read first or reveal the answer now.">Core question</SectionHeading>
          <StatusChip>{data.content.contentMode.replaceAll('_', ' ')}</StatusChip>
        </div>
        <h2 className="mt-4 text-lg font-semibold">{data.content.coreQuestion}</h2>
        <textarea
          className="mt-4 min-h-20 w-full resize-y rounded-lg border border-line bg-white p-3 text-sm outline-none focus:border-lexis"
          onChange={(event) => setPrediction(event.target.value)}
          placeholder="Optional: write your prediction before reading."
          value={prediction}
        />
        <button className="mt-3 text-sm font-semibold text-lexis" onClick={() => setShowKnowledgeAnswer((current) => !current)} type="button">
          {showKnowledgeAnswer ? 'Hide knowledge answer' : 'Reveal knowledge answer'}
        </button>
        {showKnowledgeAnswer && <p className="mt-3 rounded-lg bg-lexis-soft p-4 text-sm leading-6 text-lexis">{data.content.knowledgeTakeaway}</p>}
      </Card>


      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.65fr)_minmax(300px,0.9fr)]">
        <Card className="p-5 md:p-7">
          <SectionHeading subtitle={`Generated by ${data.provider} and saved in PostgreSQL.`}>Context reading</SectionHeading>
          <article className="mt-5 rounded-lg border border-[#e7e2d7] bg-[#fffdf8] p-5 md:p-7">
            <h2 className="text-xl font-semibold">{data.content.title}</h2>
            <p className="mt-5 text-[15px] leading-7 text-[#34393d]">{data.content.readingText}</p>
          </article>
          <div className="mt-6">
            <SectionHeading subtitle="Each word keeps the sense and role confirmed in the topic proposal.">Lesson vocabulary</SectionHeading>
            <div className="mt-3 grid gap-2 sm:grid-cols-2">
              {data.content.wordUsages
                .filter((usage) => usage.role === 'anchor' || usage.role === 'support')
                .map((usage) => (
                  <div className="rounded-lg border border-line p-3" key={usage.word}>
                    <div className="flex items-center justify-between gap-2">
                      <WordChip>{usage.word}</WordChip>
                      <span className="text-[11px] capitalize text-lexis">{usage.role}</span>
                    </div>
                    <p className="mt-2 text-xs text-ink-muted">{usage.meaningZh} · {usage.partOfSpeech}</p>
                    <p className="mt-1 text-xs leading-5 text-ink-muted">{usage.topicRole}</p>
                  </div>
                ))}
            </div>
          </div>
        </Card>

        <div className="grid content-start gap-5">
          <Card className="p-5">
            <SectionHeading subtitle="Additional words include Chinese support.">Vocabulary aid</SectionHeading>
            <dl className="mt-4 space-y-3 text-sm">
              {data.content.unfamiliarWords.map((item) => <div key={item.word}><dt className="font-semibold">{item.word}</dt><dd className="mt-1 text-ink-muted">{item.meaningZh}</dd></div>)}
            </dl>
          </Card>
          <Card className="p-5">
            <SectionHeading subtitle="Sources are stored with the lesson and shown after the reading.">Knowledge sources</SectionHeading>
            <div className="mt-4 grid gap-3">
              {data.content.knowledgeSources.map((source) => (
                <a
                  className="rounded-lg border border-line p-3 text-xs leading-5 text-ink-muted transition hover:border-lexis/40 hover:text-lexis"
                  href={source.url}
                  key={source.id}
                  rel="noreferrer"
                  target="_blank"
                >
                  <strong className="block text-ink">{source.title}</strong>
                  <span>{source.publisher} · {source.version}</span>
                </a>
              ))}
            </div>
          </Card>
          <Card className="p-5">
            <SectionHeading>Grammar analysis</SectionHeading>
            <ul className="mt-4 grid gap-3 text-sm leading-6 text-ink-muted">{data.content.grammarAnalysis.map((item) => <li className="rounded-lg bg-surface-muted p-3" key={item}>{item}</li>)}</ul>
          </Card>
        </div>
      </div>

      <Card className="mt-5 p-5 md:p-7">
        <SectionHeading subtitle="Submit one exercise at a time. Each answer and its feedback are saved immediately.">Exercises</SectionHeading>
        <div className="mt-5 grid gap-4 md:grid-cols-2">
          {data.content.exercises.map((exercise, index) => {
            const feedback = savedFeedback.get(index)
            const answer = answers[index] ?? feedback?.answer ?? ''
            const isSubmitting = submitAnswer.isPending
              && submitAnswer.variables?.exerciseIndex === index

            return (
              <section className="rounded-lg border border-line p-4" key={exercise.type}>
                <div className="flex items-center justify-between gap-3">
                  <span className="text-xs font-semibold text-lexis">{exerciseLabels[exercise.type]}</span>
                  {feedback && <StatusChip tone={feedback.isCorrect ? 'success' : 'warning'}>{feedback.isCorrect ? 'Correct' : 'Review'}</StatusChip>}
                </div>
                <h3 className="mt-2 text-sm font-semibold leading-6">{exercise.question}</h3>

                {exercise.options.length > 0 ? (
                  <div className="mt-3 grid gap-2">
                    {exercise.options.map((option) => (
                      <button
                        aria-pressed={answer === option}
                        className={`rounded-md border p-3 text-left text-xs transition ${answer === option ? 'border-lexis bg-lexis-soft text-lexis' : 'border-transparent bg-surface-muted text-ink-muted hover:border-line'}`}
                        key={option}
                        onClick={() => setAnswers((current) => ({ ...current, [index]: option }))}
                        type="button"
                      >
                        {option}
                      </button>
                    ))}
                  </div>
                ) : (
                  <textarea
                    className="mt-3 min-h-24 w-full resize-y rounded-lg border border-line bg-white p-3 text-sm outline-none transition focus:border-lexis"
                    onChange={(event) => setAnswers((current) => ({ ...current, [index]: event.target.value }))}
                    placeholder={`Use one of: ${data.content.targetWords.join(', ')}`}
                    value={answer}
                  />
                )}

                <PrimaryButton
                  className="mt-3 w-full"
                  disabled={!answer.trim() || submitAnswer.isPending}
                  onClick={() => submitAnswer.mutate(
                    { exerciseIndex: index, answer },
                    {
                      onSuccess: (result) => {
                        setSubmittedFeedback((current) => ({
                          ...current,
                          [index]: result,
                        }))
                      },
                    },
                  )}
                >
                  {isSubmitting ? 'Checking…' : feedback ? 'Check again' : 'Check answer'}
                </PrimaryButton>

                {feedback && (
                  <div className={`mt-3 rounded-lg border p-3 text-xs leading-5 ${feedback.isCorrect ? 'border-lexis/20 bg-lexis-soft text-lexis' : 'border-warning/20 bg-warning-soft text-warning'}`}>
                    {feedback.feedbackText}
                  </div>
                )}
              </section>
            )
          })}
        </div>
        {submitAnswer.isError && <p className="mt-4 text-xs text-danger">{submitAnswer.error instanceof Error ? submitAnswer.error.message : 'The answer could not be saved.'}</p>}
        <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-5">
          <p className="text-xs text-ink-muted">
            {savedFeedback.size === data.content.exercises.length
              ? 'All answers are saved. Complete the lesson to create the final summary.'
              : 'The attempt remains a resumable draft until all four answers are saved.'}
          </p>
          <PrimaryButton
            disabled={savedFeedback.size !== data.content.exercises.length || completeLesson.isPending}
            onClick={() => completeLesson.mutate(undefined, {
              onSuccess: () => {
                toast.success('Lesson completed')
                navigate('/app/lessons/' + data.id + '/complete')
              },
              onError: (mutationError) => toast.error(mutationError instanceof Error ? mutationError.message : 'The lesson could not be completed.'),
            })}
          >
            {completeLesson.isPending ? 'Finishing…' : 'Complete lesson'}
          </PrimaryButton>
        </div>
        {completeLesson.isError && <p className="mt-3 text-xs text-danger">{completeLesson.error instanceof Error ? completeLesson.error.message : 'The lesson could not be completed.'}</p>}
      </Card>
    </div>
  )
}
